services:
  keycloak:
    image: elczar/clase-11380-keycloak:1.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - keycloak_data_final:/opt/keycloak/data

volumes:
  keycloak_data_final: